### ISSUE TITLE
Can you help me with this error?

### ISSUE THREAD

**Issue by NeoGeoFreak2004** [David-Vandensteen/neocore#7]
Hey yall, so anyways i installed the neocore sdk on my windows computer and it went well, but when i ran the mak run command it gave me a error, the error says: FATAL: Can't create /Users/thepl/AppData/Local/Temp/neocore/hello/crt0_cd.o: No such file or directory
make: *** [/Users/thepl/AppData/Local/Temp/neocore/hello/crt0_cd.o] Error 1
idk what to do for this error, so can you please help me!

**Comment by David-Vandensteen** [comment]
Hi,

Can y give me the output of this command :
`%appdata%\neocore\bin\cygpath -u %temp%`

**Comment by NeoGeoFreak2004** [comment]
/cygdrive/c/Users/thepl/AppData/Local/Temp

**Comment by David-Vandensteen** [comment]
I'm rewriting the builder script,  you  can test the develop branch.

**Comment by NeoGeoFreak2004** [comment]
thanks, the example programs compiled correctly, and the develop branch is great, but i have a question to ask. i was typing in the command to compile a program, but when i try to run the command on the program i created, it gives me an error. the error says: C:/Users/thepl/AppData/Local/Temp/neocore/myfirst/crt0_cd.o(.text+0x10e): undefined reference to `bkp_data'
IDK What this means so can you tell me what is wrong. Also will you add Graphic sprite support and also can you add save support to the sdk.

**Comment by David-Vandensteen** [comment]
I think the NEOCORE_INIT macro is not called (or maybe from a function)
The first thing to do after the includes is to call this macro

To integrate sprites, my library uses DATlib (another library for Neogeo), read pages 13-19 of this documentation: %appdata%\neocore\neodev-sdk\doc\DATlib-LibraryReference.pdf

The mentioned Framer tool is available here:
%appdata%\neocore\neodev-sdk\m68k\bin\Framer.exe

The Animator tool is available here:
%appdata%\neocore\neodev-sdk\m68k\bin\Animator.exe

Regarding the save, are you talking about the memory card?
I've planned but it's not my priority at the moment...

**Comment by NeoGeoFreak2004** [comment]
Yes, I am talking about the memory card save feature, also when i try to display text into my code, it does not want to display the text on the screen, can you tell me how to do that? is there a display text function in the sdk?

**Comment by David-Vandensteen** [comment]
See hello project sample

**Comment by NeoGeoFreak2004** [comment]
I did and it worked really well on Mame! thanks, also can i run my projects made from this sdk via the original neo-geo cd hardware?

**Comment by David-Vandensteen** [comment]
You can test on real hardware ...
With "mak iso", the script display the generated cue file & the iso file path

**Comment by NeoGeoFreak2004** [comment]
thanks, i am going to burn the compiled iso to a cd-r disc. Also i have two questions. 
1.How do i get to display sprites on the screen and move them around with the joypad?
2.how can i play music, like say the fm samples used on the aes or do i have to convert the songs to cdda?

**Comment by David-Vandensteen** [comment]
1.For moving sprite with joypad, see "sprite" & "bullet" projects
2.FM & PCM driver is not implemented yet...

For CDDA, im currently work on this ([https://www.youtube.com/watch?v=d0YSiFH_w8M])
Its available in projects\CDDA, but it's not ready for now ... you don't hear anything if you run the project

Please, you can now switch on the master branch, i ve merged the builder mak scripts updates from develop

**Comment by NeoGeoFreak2004** [comment]
Thank you for the comment, also i don't know how to use the datlib library so is there any tutorials on how to use the datlib library?

**Comment by David-Vandensteen** [comment]
All you need for use DATlib is in these docs:

%appdata%\neocore\neodev-sdk\docdevkit.pdf
%appdata%\neocore\neodev-sdk\\DATlib-LibraryReference.pdf

If y want a DATlib sample (without using my lib), check the DATdemo (available in projects)
