### ISSUE TITLE
Graphic conversion issue.

### ISSUE THREAD

**Issue by NeoGeoFreak2004** [David-Vandensteen/neocore#80]
Hey, so anyways i was trying to convert a png file into a sprite using the buildchar program. but when i try to convert the sprite into a png, it gives me an error. the error says: Invalid character in the given encoding. Line 1, position 1.
Idk what this means so can you try to figure out what's causing the issue to pop up?

**Comment by David-Vandensteen** [comment]
Sure, give me the png.

**Comment by NeoGeoFreak2004** [comment]
![01](https://user-images.githubusercontent.com/76540678/212781062-e87ab9f8-11e6-4ed4-99bd-ad762fcc65f6.png)
here is the file that i tried to convert with the buildchar program.

**Comment by David-Vandensteen** [comment]
Hi,
Your file have some tiles with overload colors.
I paste the content of the documentation about file format spécification to build whith buildchar:

_About input files format:
Picture files used in chardata.xml must be PNG format, 32bppArgb. Define transparency by pink color
(#ff00ff), or simply use transparency. Size must be multiples of 16.
About colors:
There is no limits color wise, as long as each tile is transparency + 15 colors max, you can use pics with
hundreds of colors.
If your file is rejected for using too many colors per tile, erroneous tiles will be shown in a reject.png file_

**Comment by David-Vandensteen** [comment]
Hi,

Here is a way to solve the problem..
Update Neocore to version 1.0.4 from the master or release/1.0.4 branch
Delete the build directory if it exists
Compile the hello sample for example (so that the kit installs and compiles the lib)
go to the samples\issue_80 folder
mak
Normally you should get a sprite reject type error
Run the fix-background.bat script
mak run

**Comment by David-Vandensteen** [comment]
Fixed on v1.0.4
